## 16 GPIO на разъёмах: GPIO16_tri_io[0..15]
## Источник: astranome/Astra_S9_FPGA_Base — HDMI18.3.srcs/constrs_1/new/system.xdc
##
## Индексы [2]/[3] и [14]/[15] разведены иначе, чем в trebisky_emio_gpio47.xdc
## (тот файл — 47 линий, этот — первые 16 для daughter board).

set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO16_tri_io[0]}]
set_property PACKAGE_PIN T11 [get_ports {GPIO16_tri_io[0]}]
set_property PACKAGE_PIN T10 [get_ports {GPIO16_tri_io[1]}]
set_property PACKAGE_PIN T12 [get_ports {GPIO16_tri_io[2]}]
set_property PACKAGE_PIN U12 [get_ports {GPIO16_tri_io[3]}]
set_property PACKAGE_PIN R19 [get_ports {GPIO16_tri_io[4]}]
set_property PACKAGE_PIN V13 [get_ports {GPIO16_tri_io[5]}]
set_property PACKAGE_PIN Y16 [get_ports {GPIO16_tri_io[6]}]
set_property PACKAGE_PIN Y17 [get_ports {GPIO16_tri_io[7]}]
set_property PACKAGE_PIN W14 [get_ports {GPIO16_tri_io[8]}]
set_property PACKAGE_PIN Y14 [get_ports {GPIO16_tri_io[9]}]
set_property PACKAGE_PIN T16 [get_ports {GPIO16_tri_io[10]}]
set_property PACKAGE_PIN U17 [get_ports {GPIO16_tri_io[11]}]
set_property PACKAGE_PIN V15 [get_ports {GPIO16_tri_io[12]}]
set_property PACKAGE_PIN W15 [get_ports {GPIO16_tri_io[13]}]
set_property PACKAGE_PIN V12 [get_ports {GPIO16_tri_io[14]}]
set_property PACKAGE_PIN W13 [get_ports {GPIO16_tri_io[15]}]
